### ISSUE TITLE
SubjectCustom drag events do not come through EditableAnnotation

### ISSUE THREAD

**Issue by KentDi808** [susielu/react-annotation#10]
As a prototype I created a custom subject and used `AnnotationCalloutCustom` to put it on the page. Moving it around I do not get the `props` value in the `onDragEnd` event. Without these values state cannot be updated and position later persisted to a data store.

**Comment by susielu** [comment]
There was a typo, this should be resolved in 1.1.2, let me know if you have any issues using it.

**Comment by KentDi808** [comment]
Your changes fixed the issue. Thank you very much.
