### ISSUE TITLE
Bug: Codepen imports failing

### ISSUE THREAD

**Issue by susielu** [susielu/react-annotation#12]

**Comment by KentDi808** [comment]
It would also be nice if we could import `react-annotation` in [Observable](https://beta.observablehq.com) notebooks.

**Comment by susielu** [comment]
This has been resolved.

@KentDi808 I would recommend using d3-annotation instead in observable notebooks, example here made by @hydrosquall 🙌 : https://beta.observablehq.com/@hydrosquall/d3-annotation-with-d3-line-chart
