### ISSUE TITLE
Annotation Background

### ISSUE THREAD

**Issue by STPMartin** [susielu/react-annotation#17]
Hi Susie -- thank you for putting this great library together! Is it possible to add a background color to an annotation to set the titleColor and labelColor against? I have looked through the docs and a few of the examples provided. Any help would be greatly appreciated!

**Comment by susielu** [comment]
There's a rect behind the annotation you can access with the `.annotation-not-bg` class and set a different `fill` color to using css. Let me know if I'm misunderstanding the question though.

**Comment by STPMartin** [comment]
Thank you for getting back to me! I see the .annotation-not-bg class I just can't figure out how to override the default fill and opacity styles.

**Comment by susielu** [comment]
You can just override it with css. Css styles have higher priority than svg
attribute properties.

**Comment by STPMartin** [comment]
I have tried to override with css, but when I input styles to the .annotation-not-bg class in my style sheet they don't override the rect's properties. Do you have any idea why this might be happening? Thank you again for your help.

**Comment by susielu** [comment]
Are you able to put together an example? It seems to be working on the docs and in this codepen. https://codepen.io/susielu/pen/KxLJRM

**Comment by STPMartin** [comment]
Ugh. I'm embarrassed to admit this, but I had a syntax error that was preventing styles from being rendered properly. Thank you so much Susie for your help and patience!

**Comment by susielu** [comment]
👍 glad you solved the puzzle. Will close this issue.
