### ISSUE TITLE
Annotate an image?

### ISSUE THREAD

**Issue by maka-io** [susielu/react-annotation#8]
This looks like a fantastic app, but I'm looking through the documentation (maybe I'm missing it) and am trying to find a clear way to import an image on which to annotate.  Then a way to export it... although I could figure out how to export it on my own.

Any suggestions?

Thanks!

**Comment by KentDi808** [comment]
@maka-io You can annotate an image. What I have done is create an SVG and add an image element to it. The tricky part may be populating the image element with your image. Once the image is in the SVG you can just annotate it like any other SVG. I am using [save-svg-as-png](https://www.npmjs.com/package/save-svg-as-png) to save the annotated SVG.

**Comment by susielu** [comment]
Hey Matt, this is just a library to create annotations in SVG. It's not a full-fledged app for annotating images, although that's long been on my to do list to create. @KentDi808 do you have a sample app for doing this anywhere publicly? Maybe I can riff off of that and start building it out.

**Comment by KentDi808** [comment]
@susielu At the moment, we are using your library (very successfully) to do annotations in our application and it would be hard to post a portion of it. I'll see if I can do a small app to show the process. I would do it on [Observable](https://beta.observablehq.com) but I am still having trouble getting some npm modules to import.

More soon.

**Comment by susielu** [comment]
Excellent, great to hear it's working well in your app 👌

**Comment by maka-io** [comment]
@KentDi808 I ended up rolling my own simply by creating three canvas (one for the annotations, one for the background image, and the last as the amalgamation of the first two).

@susielu Thanks for your input! I  did end up getting this working for an image, and very nicely I may add supporting importing an image, annotating it, and exporting it to be saved as png/jpeg/etc (base64).

I'm cooking up a wish list (dotted line option, drawing just a arrow/line, click to edit text, etc.) which I hope I can make some PRs in the short future.

**Comment by susielu** [comment]
Awesommmmmmmee! Thanks for the update. Looking forward to seeing your wish list.

**Comment by susielu** [comment]
For those interested in this use case, here's a getting started example by @KentDi808 
 https://github.com/KentDi808/image-annotate/tree/master 🙏😊
